theme: jekyll-theme-cayman
title: ShellSage
description: Intelligent Command-Line Assistant for VS Code
show_downloads: true
google_analytics:
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-algolia

# Algolia search
algolia:
  application_id: YOUR_APPLICATION_ID
  index_name: shellsage
  search_only_api_key: YOUR_SEARCH_ONLY_API_KEY
  nodes_to_index: 'p,h1,h2,h3,h4,h5,h6,code'

# Site settings
author:
  name: Zhang Hongping
  email: zhanghongping1982@gmail.com

# Comments settings
comments:
  provider: giscus
  giscus:
    repo: hongping1963-source/shellsage
    repo-id: R_kgDONhk6XA
    category: General
    category-id: DIC_kwDONhk6XM4ClgRw
    mapping: pathname
    reactions-enabled: 1
    theme: preferred_color_scheme
    language: zh-CN

# Navigation
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs
  - title: Blog
    url: /blog
  - title: Examples
    url: /examples
  - title: GitHub
    url: https://github.com/hongping1963-source/shellsage
