theme: jekyll-theme-cayman
title: ShellSage - Smart Command-Line Assistant for VS Code
description: Boost your terminal productivity with AI-powered command suggestions, error prevention, and intelligent assistance
show_downloads: true
google_analytics:
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
tagline: Smart Command-Line Assistant for VS Code
keywords: vscode extension, terminal, command line, AI assistant, productivity tool
twitter:
  username: hongping1963
  card: summary_large_image
social:
  name: Zhang Hongping
  links:
    - https://github.com/hongping1963-source
    - https://twitter.com/hongping1963

# Site settings
author:
  name: Zhang Hongping
  email: zhanghongping1982@gmail.com
  website: https://hongping1963-source.github.io/shellsage/

# Site maintainer
maintainer:
  email: zhanghongping1982@gmail.com

# Comments settings
comments:
  provider: giscus
  giscus:
    repo: hongping1963-source/shellsage
    repo-id: R_kgDONhk6XA
    category: General
    category-id: DIC_kwDONhk6XM4ClgRw
    mapping: pathname
    reactions-enabled: 1
    theme: preferred_color_scheme
    language: zh-CN

# Navigation
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs
  - title: Blog
    url: /blog
  - title: Books
    url: /books
  - title: Examples
    url: /examples
  - title: GitHub
    url: https://github.com/hongping1963-source/shellsage
