theme: jekyll-theme-cayman
title: ShellSage
description: Your intelligent terminal companion in VS Code
baseurl: "/shellsage"
url: "https://hongping1963-source.github.io"
show_downloads: true
github:
  repository_url: https://github.com/hongping1963-source/shellsage
  zip_url: https://github.com/hongping1963-source/shellsage/archive/main.zip
  tar_url: https://github.com/hongping1963-source/shellsage/archive/main.tar.gz

# Navigation
navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Installation
    url: /installation/
  - title: Features
    url: /features/
  - title: Blog
    url: /blog/
  - title: FAQ
    url: /faq/
  - title: Contributing
    url: /contributing/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_docs"
    values:
      layout: doc
  - scope:
      path: "_posts"
    values:
      layout: post
